### PR TITLE
Add error type

### LINKED ISSUE #9: Errors missing in typings
Like in #7 if the API may return an error like
```js
{
  code: 400,
  name: 'Bad Request',
  description: 'You are limited to 500 characters only, sorry'
}
```
This is missing in the typings.

### PR DESCRIPTION
**Pull request by D3SOX**
Resolves #9

### CODE REVIEW

**Comment by HarutoHiroki** [comment]
Not needed, the code should already return the error as a JSON if detected.

**Comment by D3SOX** [comment]
The code does, but the typings are wrong. I use this library in a TypeScript project.
It might be unnecessary for the `Promise<JSON>` types but for the ones with `Promise<Buffer>` it's required to correctly use it without type errors.

**Comment by HarutoHiroki** [comment]
Then a quick fix should be adding JSON to the ones with `Promise<Buffer>` instead of having to create a new interface for just errors. I'll address this in the next publish

**Comment by HarutoHiroki** [comment]
I'm not 100% familiar with TS, sorry for the inconvenience.

**Comment by D3SOX** [comment]
Actually, the JSON type is also wrong. I haven't used one of the endpoints that returns a JSON yet, but I just tried it and `JSON` is definitely the wrong type for this. Either create an interface for each one or use `any`.
`JSON` in this context refers to the internal JavaScript [`JSON` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON)

**Comment by D3SOX** [comment]
I will make a new PR for this, which also fixes the JSON response types

**Comment by HarutoHiroki** [comment]
Just googled, it's `JSONResponse` (thanks stackoverflow). Try that out!

**Comment by HarutoHiroki** [comment]
You can also assign them manually that's fine too.

**Comment by D3SOX** [comment]
I'm creating proper types for this now. btw color is also wrong atm, it returns a `Buffer` not a JSON.

**Comment by HarutoHiroki** [comment]
I'm pretty sure the `/color/hex` endpoint returns a JSON, can you double-check on that?

**Comment by D3SOX** [comment]
`/color/hex` and `/fml` does indeed return a `Buffer` for me.

**Comment by D3SOX** [comment]
These types work for me now, Naming it `Error` was also a kinda dumb idea as it already exists.

**Comment by D3SOX** [comment]
Ok I think I disovered another bug. When calling `coffee` before calling `color` or `fml` it returns a `Buffer`.

Using this code
```js
alexClient.image.coffee().then(test => {
  console.log('coffee', test);
});
alexClient.others.fml().then(test => {
  console.log('fml', test);
});
alexClient.others.color('d4d9cb').then(test => {
  console.log('color', test);
});
```

returned
```
fml <Buffer 0a 3c 21 64 6f 63 74 79 70 65 20 68 74 6d 6c 3e 0a 3c 74 69 74 6c 65 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 0a 3c 68 31 3e ... 53 more bytes>
color <Buffer 0a 3c 21 64 6f 63 74 79 70 65 20 68 74 6d 6c 3e 0a 3c 74 69 74 6c 65 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 0a 3c 68 31 3e ... 53 more bytes>
coffee { file: 'https://coffee.alexflipnote.dev/ZyicxFeG0DI_coffee.jpg' }
```

**Comment by HarutoHiroki** [comment]
implemented with credits

**Comment by D3SOX** [comment]
That was unexcepted but nice thx for the update

**Pull request closed without merging**
